// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Seq$TypeAligned = require("./Seq.bs.js");

function Make(F) {
  var singleton = function (x) {
    return /* Snoc */[/* tuple */[
              /* SNil */0,
              x
            ]];
  };
  var snoc = function (xs, x) {
    return /* Snoc */[/* tuple */[
              xs,
              x
            ]];
  };
  var consOrSnoc = /* `Snoc */[
    925929103,
    snoc
  ];
  var viewRight = function (param) {
    if (param) {
      var match = param[0];
      return /* ConsR */[/* tuple */[
                match[0],
                match[1]
              ]];
    } else {
      return /* EmptyR */0;
    }
  };
  var view = /* `Right */[
    -57574468,
    viewRight
  ];
  return Seq$TypeAligned.Make({
              F: F,
              empty: /* SNil */0,
              singleton: singleton,
              consOrSnoc: consOrSnoc,
              view: view
            });
}

exports.Make = Make;
/* No side effect */
